name: Deploy to server

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    env:
      NAME: EjemploDeploy

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo ${{ env.NAME}}"

  second_jobs:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: first_jobs
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo Segundo"
