name: Deploy to server

on: push

jobs:
  first_jobs:
    name: Despliegue con GitHub Action
    runs-on: ubuntu-latest

    env:
      NAME: EjemploDeploy

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo ${{ env.NAME}}"

      - name: Listar directorios
        run: ls -al

      - name: Action
        uses: actions/checkout@v5

      - name: Listar directorios despues del action
        run: ls -al

  second_jobs:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: first_jobs
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo Segundo"
