name: Deploy to server

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        message: ["HTML", "CSS", "JavaScript"]

    steps:
      - name: Imprimir mensaje
        run: echo "${{ matrix.message }}"
